#!/bin/sh
### BEGIN INIT INFO
# Provides:          netmicroscope-daemon
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: netmicroscope daemon
# Description:       enable netmicroscope-daemon (nmd) data collection service
### END INIT INFO
case "$1" in
  start)
	/usr/local/bin/nmd start
    ;;
  stop)
	/usr/local/bin/nmd stop
    ;;
  restart)
	/usr/local/bin/nmd restart
    ;;
  status)
	/usr/local/bin/nmd status
    ;;
 *)
    echo "Usage: /etc/init.d/netmicroscope-daemon {start|stop|restart|status}"
    exit 1
    ;;
esac
exit 0
